apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tooljet-db-postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: operator-cloudnative-pg
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tooljet/db/postgres/local
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tooljet-app
  namespace: flux-system
spec:
  dependsOn:
    - name: tooljet-db-postgres
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tooljet/app/local
  prune: true
  wait: true