# on actual server we need to encrypt this using sops or others mechanism
apiVersion: v1
kind: Secret
metadata:
    name: postgres-tooljet-secrets
    namespace: tooljet
stringData:
    db_name: pg-tooljet
    db_host: pg-tooljet-rw.tooljet.svc.cluster.local
    db_password: pguserpassword
    db_port: "5432"
    db_user: pguser